config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  #get 'books' => 'books#index'
  #post 'books' => 'books#create'
  #get 'books/:id' => 'books#show', as: 'book'
  #patch 'books/:id' => 'books#update', as: 'update_book'
  #delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  #get 'books/:id/edit' => 'books#edit', as: 'edit_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:create] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:update] = "Book was successfully updated."
      redirect_to book_path(book.id)
    else
      @book = book
      render :edit
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:destroy] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="edit_book">
  <h1>Editing Book</h1>
    <% if @book.errors.any? %>
    <div class="error_pop">
      <% if @book.errors.count==1 %>
        <p class="error_p"><%= @book.errors.count %>&nbsp;error prohibited this book from being saved:</p>
      <% else %>
        <p class="error_p"><%= @book.errors.count %>&nbsp;errors prohibited this book from being saved:</p>
      <% end %>
      <ul class="error_ul">
        <% @book.errors.full_messages.each do |message| %>
          <li class="error_li"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
    <div class="edit_p">
      <p>Title</p>
      <%= f.text_field :title %>
    </div>
    <div class="edit_p">
      <p>Body</p>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Update Book' %>
  <% end %>
  <div class="edit_link">
    <ul>
      <li><%= link_to "Show", book_path(@book.id), class: "botton" %></li>
      <li><%= link_to "Back", "/books", class: "botton" %></li>
    </ul>
  </div>
</div>

app/views/books/index.html.erb
<div class="destroy">
  <%= flash[:destroy] %>
</div>
<div class="index_tables">
  <h1>Books</h1>
  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @books.each do |book| %>
      <tr>
        <td class="data_row"><%= book.title %></td>
        <td class="data_row"><%= book.body %></td>
        <td class="data_row"><%= link_to "Show", book_path(book.id), class: "botton" %></td>
        <td class="data_row"><%= link_to "Edit", edit_book_path(book.id), class: "botton" %></td>
        <td class="data_row"><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?", class: "botton" %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="create_book">
  <h2>New book</h2>
  <% if @book.errors.any? %>
    <div class="error_pop">
      <% if @book.errors.count==1 %>
        <p class="error_p"><%= @book.errors.count %>&nbsp;error prohibited this book from being saved:</p>
      <% else %>
        <p class="error_p"><%= @book.errors.count %>&nbsp;errors prohibited this book from being saved:</p>
      <% end %>
      <ul class="error_ul">
        <% @book.errors.full_messages.each do |message| %>
          <li class="error_li"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book do |f| %>
    <div class="create_p">
      <p>Title</p>
      <%= f.text_field :title %>
    </div>
    <div class="create_p">
      <p>Body</p>
      <%= f.text_area :body %>
    </div>
    <%= f.submit 'Create Book' %>
  <% end %>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Body</p>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="show_book">
    <div class="create">
        <%= flash[:create] %>
    </div>
    <div class="update">
        <%= flash[:update] %>
    </div>
    <p class="show_p"><b>Title:</b> <%= @book.title %></p>
    <p class="show_p"><b>Body:</b> <%= @book.body %></p>
</div>
<div class="show_link">
    <ul>
        <li><%= link_to "Edit", edit_book_path(@book), class: "botton" %></li>
        <li><%= link_to "Back", "/books", class: "botton" %></li>
    </ul>
<div>

app/views/homes/top.html.erb
<h2>ようこそ Bookers へ！</h2>
<p><b>Bookers</b> では、様々な書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>
<%= link_to "start", "/books", class: "botton" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>